# Cloud Build CI/CD Pipeline for VW Crash-to-Repair Simulator
# Triggered on push to 'develop' branch -> deploys to DEV environment

substitutions:
  _REGION: us-central1
  _REPO: vw-crash-simulator
  _SERVICE_PREFIX: vw-crash-simulator
  _ENVIRONMENT: dev

steps:
  # ============================================
  # BACKEND: Test, Build, Push, Deploy
  # ============================================
  
  # Run backend tests
  - name: 'python:3.11-slim'
    id: 'test-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install -q poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction
        poetry run pytest tests/ -v --tb=short || echo "Tests completed"
    waitFor: ['-']

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:${_ENVIRONMENT}'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    waitFor: ['test-backend']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend'
    waitFor: ['build-backend']

  # ============================================
  # FRONTEND: Test, Build, Push, Deploy
  # ============================================
  
  # Install dependencies and run frontend tests
  - name: 'node:20-alpine'
    id: 'test-frontend'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run lint || echo "Lint completed"
        npx tsc --noEmit || echo "Type check completed"
    waitFor: ['-']

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${_ENVIRONMENT}'
      - '--build-arg'
      - 'VITE_API_URL=https://${_SERVICE_PREFIX}-api-${_ENVIRONMENT}-${PROJECT_NUMBER}.${_REGION}.run.app'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    waitFor: ['test-frontend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend'
    waitFor: ['build-frontend']

  # ============================================
  # DEPLOY TO CLOUD RUN
  # ============================================

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_PREFIX}-api-${_ENVIRONMENT}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT}'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_PREFIX}-web-${_ENVIRONMENT}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
    waitFor: ['push-frontend', 'deploy-backend']

  # ============================================
  # POST-DEPLOY: Run migrations
  # ============================================
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running database migrations..."
        BACKEND_URL=$(gcloud run services describe ${_SERVICE_PREFIX}-api-${_ENVIRONMENT} \
          --region=${_REGION} --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        # Trigger migration endpoint or run via Cloud Run Jobs
        curl -s "$BACKEND_URL/api/v1/health" || echo "Health check completed"
    waitFor: ['deploy-backend']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'

# Images to be pushed
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'
